<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <VersionPrefix>0.1.0</VersionPrefix>
        <VersionSuffix>$([System.DateTime]::UtcNow.ToString("yyyyMMdd"))</VersionSuffix>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
        <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)/..'))=Dev:/playnite-amazon-clientless-plugin</PathMap>
    </PropertyGroup>

    <ItemGroup>
        <None Include="Localization\*\*.ftl">
            <Generator>MSBuild:Compile</Generator>
            <SubType>Designer</SubType>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="..\third_party\Localization\*\*.ftl">
            <Link>Localization\%(RecursiveDir)\%(Filename)%(Extension)</Link>
            <Generator>MSBuild:Compile</Generator>
            <SubType>Designer</SubType>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="..\third_party\CommonLocalization\*\*.ftl">
            <Link>Localization\%(RecursiveDir)\%(Filename)%(Extension)</Link>
            <Generator>MSBuild:Compile</Generator>
            <SubType>Designer</SubType>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <None Update="extension.toml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="..\LICENSE.md">
            <Link>LICENSE</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="..\ThirdPartyLicenses.txt">
            <Link>ThirdPartyLicenses.txt</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <Compile Include="..\third_party\twl.py\sds-proto2.g.cs" Link="Shared\Generated\sds-proto2.g.cs"/>
    </ItemGroup>
    <ItemGroup Label="compileInclude3p">
        <Compile Include="..\third_party\Playnite_mod\Commands.cs" Link="Shared\Playnite_mod\Commands.cs"/>
        <Compile Include="..\third_party\Playnite_mod\FileSystem.cs" Link="Shared\Playnite_mod\FileSystem.cs"/>
        <Compile Include="..\third_party\Playnite_mod\Paths.cs" Link="Shared\Playnite_mod\Paths.cs"/>
        <Compile Include="..\third_party\Playnite_mod\ProcessMonitor.cs" Link="Shared\Playnite_mod\ProcessMonitor.cs"/>
        <Compile Include="..\third_party\Playnite_mod\ProcessStarter.cs" Link="Shared\Playnite_mod\ProcessStarter.cs"/>
        <Compile Include="..\third_party\Playnite_mod\Xaml.cs" Link="Shared\Playnite_mod\Xaml.cs"/>
        <Compile Include="..\third_party\Playnite_mod\Extensions\ProcessExtensions.cs" Link="Shared\Playnite_mod\ProcessExtensions.cs"/>
        <Compile Include="..\third_party\Playnite_mod\Extensions\StringExtensions.cs" Link="Shared\Playnite_mod\StringExtensions.cs"/>
        <Compile Include="..\third_party\playnite-common-plugin\src\Enums\ClearCacheTime.cs" Link="Shared\Enums\ClearCacheTime.cs"/>
        <Compile Include="..\third_party\playnite-common-plugin\src\Enums\DownloadAction.cs" Link="Shared\Enums\DownloadAction.cs" />
        <Compile Include="..\third_party\playnite-common-plugin\src\Enums\DownloadStatus.cs" Link="Shared\Enums\DownloadStatus.cs" />
        <Compile Include="..\third_party\playnite-common-plugin\src\CommonHelpers.cs" Link="Shared\CommonHelpers.cs"/>
        <Compile Include="..\third_party\playnite-common-plugin\src\Encryption.cs" Link="Shared\Encryption.cs"/>
         <Compile Include="..\third_party\playnite-common-plugin\src\IconExtension.cs">
            <Link>Shared\IconExtension.cs</Link>
        </Compile>
        <Compile Include="..\third_party\playnite-common-plugin\src\LocalizationManager.cs" Link="Shared\LocalizationManager.cs"/>
        <Compile Include="..\third_party\playnite-common-plugin\src\LocalizeExtension.cs" Link="Shared\LocalizeExtension.cs"/>
        <Page Include="..\third_party\playnite-common-plugin\src\NumericInput.xaml">
            <Link>Shared\NumericInput.xaml</Link>
            <SubType>Designer</SubType>
            <Generator>MSBuild:Compile</Generator>
        </Page>
        <Compile Include="..\third_party\playnite-common-plugin\src\NumericInput.xaml.cs" Link="Shared\NumericInput.xaml.cs">
            <DependentUpon>NumericInput.xaml</DependentUpon>
        </Compile>
        <Compile Include="..\third_party\playnite-common-plugin\src\RetryHandler.cs" Link="Shared\RetryHandler.cs"/>
        <Compile Include="..\third_party\playnite-common-plugin\src\Serialization.cs" Link="Shared\Serialization.cs"/>
        <None Include="..\third_party\playnite-common-plugin\src\Resources\FullScreenStyles.xaml">
            <Link>Shared\Resources\FullScreenStyles.xaml</Link>
            <SubType>Designer</SubType>
            <Generator>MSBuild:Compile</Generator>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <TargetPath>Resources\FullScreenStyles.xaml</TargetPath>
        </None>
        <None Include="..\third_party\playnite-common-plugin\src\Resources\NormalStyles.xaml">
            <Link>Shared\Resources\NormalStyles.xaml</Link>
            <SubType>Designer</SubType>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <TargetPath>Resources\NormalStyles.xaml</TargetPath>
            <Generator>MSBuild:Compile</Generator>
        </None>
        <Compile Include="..\third_party\playnite-common-plugin\src\Resources\CommonIcons.cs">
            <Link>Shared\Resources\CommonIcons.cs</Link>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="ByteSize" Version="2.1.2"/>
        <PackageReference Include="LightProto" Version="1.4.0" />
        <PackageReference Include="Linguini.Bundle" Version="0.11.0"/>
        <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.333">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Playnite.SDK" Version="11.0.0-alpha14" />
        <PackageReference Include="SharpCompress" Version="0.50.4" />
        <PackageReference Include="SqlNadoAot" Version="3.1.1" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="UnifiedDownloadManagerApi">
        <HintPath>..\..\playnite-unifiedDownloadManager-plugin\src\api\bin\Release\net10.0-windows\UnifiedDownloadManagerApi.dll</HintPath>
      </Reference>
    </ItemGroup>
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="python &quot;$(ProjectDir)..\make_scripts\after_build.py&quot; $(TargetDir)" />
    </Target>
</Project>
