id = "hawkeye116477.AmazonClientless"
name = "Amazon Games Clientless library integration"
author = "hawkeye116477"
version = "_version_"
module = "AmazonClientless.dll"

# Troubleshooting link to be shown on addons view
#help_link = ""

# Source code link to be shown on addons view
#source_link = ""

[[dependencies]]
addon_id = "hawkeye116477.UDM"
min_version = "2.0"
is_optional = true
