id = "hawkeye116477.AmazonClientless"
name = "Amazon Games Clientless library integration"
author = "hawkeye116477"
version = "_version_"
module = "AmazonClientless.dll"
icon = "Resources\\icon.png"
library_icon = "Resources\\icon.png"

help_link = "https://github.com/hawkeye116477/playnite-amazon-clientless-plugin/wiki"
source_link = "https://github.com/hawkeye116477/playnite-amazon-clientless-plugin"

[[dependencies]]
addon_id = "hawkeye116477.UDM"
min_version = "2.0"
is_optional = true
